language: go
sudo: false

env:
  global:
    secure: "1PjOS0yhvV9gmkfu7Y6XEYPDkxejOb7Qe6m4BAFmLQe133DqsgvGf9TC3SItXuAQfzi5qJwgUiGotasX8wNFr2EQDO1Dzo+0rX2fNa/dLwgUam6foXx5HhXinGOHbbc6LyAaRx2D3eDqZaw3PssPZ94pMy9ALCCawXWc85sVwFQS0mPB8h6oBtVfN/Hdp7v1w7cVR89s1KYSA+T9FAYKGDaaRS9Mmihs3o52K9NsURsnPVZj7sI1Z2ir1xdOwFIvUIbl6nkRNs0lFEgrld+69+8p0bSGqcZJjo4EaVNb2F4HPm5z+zxwVPPJJn1WhqVgUFG9dQ5w2HZM6VcQynbxGqEQJRbXqY+wmCmL/HrWq0iof9hIF2gtTU2Z7CrNRDdTSmCsDMJP02sPD/XhqiKoeo8SM7GwGcayoDSzQUYXgcOeRUMtajyjLimM2u5CAu4+DbDfdip6OzinSkDgca65pYIub61abDRdOEGD+ayZkSrZofzeky+h0TakhlS2n1OZorDNTu32umGsB8iM9ycbB9WWONi034SaUimvLd3xl5qqUhEBTzhnFuTHnwN84ilHdw25V3Jm5IuU/v71hVecluRqDk5Fts+54utyyvas6M5NjsCW2mqpAkB1ScdnL1S78KITgNHF8QjDrVOrM+9O7x6dvr8qgtMZprm9Fo+NdEI="

os:
  - linux
  - osx

go:
  - 1.6
  - 1.7

script:
  - go test -v
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

notifications:
  slack:
    secure: "C5rLRy/goL4PB2gd7zmCy88EXZ4PKLTDD/vO7aMtm8jbBGMjnVFTj9EtBpILr01sa4VssD+UlE5UZhujVWSw7zed7QTZbC2AL7WoKRpetgRb8dTtGalDf0x5a1IWIM7LZHPGcj76Uog6EBysNDs/cMhAHKLUZPaRSH5SopCkScf8z/44AYoNM4/5qp9P09T4IEs1CVcAPiTd6PCZQHmGa/ek7wR7+V8+izjA/0eTb0An9Z55O4oQaqZZEcG/B1aNUaR8QT9raNbhsMdDAHwWNNGScnZvBPVWGZ1eeDdjbUd4Bd8zmuJ4jX1FqZ1APqt3F06k1ydg/1YIhiHCWM05n59VPzDV3XhF3HtLp+tsaZDOvyamwnGgCxqkvsnjp4GLF8CTzSJgwZ4/U2EXAJ4fj9XiNCCyZghSPtYNbJOvvlbpb/BNZJs8uBG9ZhzDUbrZMu+2/DYavNoXiyv4XoqJo+tnXI88GmWQPUtrG2ScmjcE3yljLIJ/ldFjlgjiYH2C/ODkLb5N86oCkhUgOe+AM+KZx7bCOBtXMOw/WDQb012keGUmUN64GfnqNh2vzosddhvJ1K/yZO8g/U0E0+AM5ByAk/IiWs0U1sHbh3r6n8J/TBn/EaL9uYDirBp0hPQ2nLUebPC85SxMxDYVT7hdhPswvGeFSugvT5KdXjAa76I="